# Generated by Django 3.1.2 on 2021-02-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='third_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
