# Generated by Django 3.1.2 on 2021-02-11 15:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210208_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cto_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cto_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cto_lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cto_logo',
            field=models.ImageField(default='default/default.png', upload_to=users.models.user_photos_dir),
        ),
        migrations.AddField(
            model_name='user',
            name='cto_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_autoservice',
            field=models.BooleanField(default=False),
        ),
    ]
