# Generated by Django 3.1.2 on 2021-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210216_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cto_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
