# Generated by Django 3.1.2 on 2021-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cto_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTORequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
