# Generated by Django 3.1.2 on 2021-02-08 13:58

import autoservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to=autoservice.models.photos_dir)),
                ('cto_id', models.CharField(max_length=50)),
            ],
        ),
    ]
