# Generated by Django 3.1.2 on 2021-01-08 13:35

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=order.models.photos_dir)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_img', to='order.order')),
            ],
        ),
    ]
