# Generated by Django 3.1.2 on 2021-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
