# Generated by Django 3.1.2 on 2021-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210214_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
