# Generated by Django 3.1.2 on 2021-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
